name: Required quality proof

on:
  pull_request:

permissions:
  contents: read

jobs:
  required-quality:
    uses: RocketsAreNostalgic/.github/.github/workflows/required-quality-wordpress-plugin.yml@f0ac073000821a0e166cdc29be818cf79bec2bb1
