name: Required quality proof

on:
  pull_request:

permissions:
  contents: read

jobs:
  required-quality:
    uses: RocketsAreNostalgic/.github/.github/workflows/required-quality-wordpress-plugin.yml@813685118eb8215fa0d6bb963fb45afb5864ee5e
