name: Required quality proof

on:
  pull_request:

permissions:
  contents: read

jobs:
  required-quality:
    uses: RocketsAreNostalgic/.github/.github/workflows/required-quality-wordpress-plugin.yml@ba124001933f7febf15262c002aefec02aab3ef8
